---
title: "Data Science Midterm"
output: github_document
---

```{r setting up R markdown}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

#Scrape a table

I want first table from this page: 
https://www.youtube.com/watch?v=2RjK6fYWdzM&feature=youtu.be
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

Extract the table - focus on 1st one

```{r}
drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

Star wars movie imdb page:
https://www.imdb.com/list/ls070150896/

(want df with title, run time, how much money it made)

```{r}
url_ = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url_)
```

Grab elements we want

```{r}
titles_vec =
  swm_html %>%
  html_nodes(css = ".lister-item-header a") %>% 
  html_text()
  
gross_r_vec =
  swm_html %>%
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

runtime_vec =
  swm_html %>%
  html_nodes(css = ".runtime") %>% 
  html_text()

swm_df = 
  tibble(
    title = titles_vec, 
    gross_rev = gross_r_vec,
    run_time = runtime_vec
  )
```

#APIs

Get some water data

https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m

```{r}
nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

#JSON structure?
#Same data but diff structure
nyc_water2 = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as.tibble()
```



```{r}

```


